# Generated by Django 5.2.7 on 2025-10-21 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_passage_title_alter_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('TF', 'True or False'), ('ID', 'Identification')], default='MCQ', max_length=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('NUM', 'Numerical Ability'), ('VER', 'Verbal Ability'), ('GEN', 'General Information')], default='GEN', max_length=3),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=0, help_text='Time limit in minutes (0 = untimed)'),
        ),
    ]
