# Generated by Django 5.2.7 on 2025-11-06 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_quizresult_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='quiz_type',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='quizresult',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='quizzes.quiz'),
        ),
    ]
