# Generated by Django 5.2.7 on 2025-10-22 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_passage_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('NUM', 'Numerical Ability'), ('VER', 'Verbal Ability'), ('ANA', 'Analytical Ability'), ('CLE', 'Clerical Ability'), ('GEN', 'General Information')], default='GEN', max_length=3),
        ),
    ]
