# Generated by Django 5.2.7 on 2025-11-11 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_quizresult_quiz_type_alter_quizresult_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(blank=True, choices=[('NUM', 'Numerical Ability'), ('VER', 'Verbal Ability'), ('ANA', 'Analytical Ability'), ('CLE', 'Clerical Ability'), ('GEN', 'General Information')], default='GEN', max_length=3, null=True),
        ),
    ]
