# Generated by Django 5.2.7 on 2025-11-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('NUM', 'Numerical Ability'), ('VER', 'Verbal Ability'), ('ANA', 'Analytical Ability'), ('CLE', 'Clerical Ability'), ('GEN', 'General Information')], default='GEN', max_length=3),
        ),
    ]
