# Generated by Django 5.2.7 on 2025-11-11 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0005_alter_quiz_quiz_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_random',
            field=models.BooleanField(default=False),
        ),
    ]
